name: NodeJS with Webpack 2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Build
      run: |
        yarn install
        yarn build
        yarn prod
      with:
          name: production
          path: ./bundler/webpack.prod.js
